# Site settings
title: Jekyll-Uno
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: "BV_blog"
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Valijanov Bahromjon'
  email: Valijanov1103@mail.ru
  twitter_username: joshgerdes
  facebook_username: baggio
  github_username:  baggio1103
  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
